version: '3.8'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_sandbox
      MYSQL_USER: ndgndg91
      MYSQL_PASSWORD: ndgndg91password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init/my.conf:/etc/mysql/my.cnf
volumes:
    mysql_data: