spring:
  application:
    name: api-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ndgndg91
    password: ndgndg91password
    url: jdbc:mysql://localhost:3306/my_sandbox
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false